version: '3'

services:
  streamlit:
    container_name: streamlit-server
    build:
      context: .
      dockerfile: .
    ports:
      - 8502:8501
    image: streamlit:1.0
    volumes:
    - ./src:/app
    tty: true